package turing.turingcodey.data.model;

import java.util.Date;

public class AliDevice {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ali_devices.id
     *
     * @mbg.generated Mon Apr 09 15:43:42 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ali_devices.device_name
     *
     * @mbg.generated Mon Apr 09 15:43:42 CST 2018
     */
    private String deviceName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ali_devices.device_id
     *
     * @mbg.generated Mon Apr 09 15:43:42 CST 2018
     */
    private String deviceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ali_devices.product_key
     *
     * @mbg.generated Mon Apr 09 15:43:42 CST 2018
     */
    private String productKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ali_devices.device_secret
     *
     * @mbg.generated Mon Apr 09 15:43:42 CST 2018
     */
    private String deviceSecret;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ali_devices.status
     *
     * @mbg.generated Mon Apr 09 15:43:42 CST 2018
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ali_devices.create_at
     *
     * @mbg.generated Mon Apr 09 15:43:42 CST 2018
     */
    private Date createAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ali_devices.update_at
     *
     * @mbg.generated Mon Apr 09 15:43:42 CST 2018
     */
    private Date updateAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ali_devices.id
     *
     * @return the value of ali_devices.id
     *
     * @mbg.generated Mon Apr 09 15:43:42 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ali_devices.id
     *
     * @param id the value for ali_devices.id
     *
     * @mbg.generated Mon Apr 09 15:43:42 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ali_devices.device_name
     *
     * @return the value of ali_devices.device_name
     *
     * @mbg.generated Mon Apr 09 15:43:42 CST 2018
     */
    public String getDeviceName() {
        return deviceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ali_devices.device_name
     *
     * @param deviceName the value for ali_devices.device_name
     *
     * @mbg.generated Mon Apr 09 15:43:42 CST 2018
     */
    public void setDeviceName(String deviceName) {
        this.deviceName = deviceName == null ? null : deviceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ali_devices.device_id
     *
     * @return the value of ali_devices.device_id
     *
     * @mbg.generated Mon Apr 09 15:43:42 CST 2018
     */
    public String getDeviceId() {
        return deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ali_devices.device_id
     *
     * @param deviceId the value for ali_devices.device_id
     *
     * @mbg.generated Mon Apr 09 15:43:42 CST 2018
     */
    public void setDeviceId(String deviceId) {
        this.deviceId = deviceId == null ? null : deviceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ali_devices.product_key
     *
     * @return the value of ali_devices.product_key
     *
     * @mbg.generated Mon Apr 09 15:43:42 CST 2018
     */
    public String getProductKey() {
        return productKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ali_devices.product_key
     *
     * @param productKey the value for ali_devices.product_key
     *
     * @mbg.generated Mon Apr 09 15:43:42 CST 2018
     */
    public void setProductKey(String productKey) {
        this.productKey = productKey == null ? null : productKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ali_devices.device_secret
     *
     * @return the value of ali_devices.device_secret
     *
     * @mbg.generated Mon Apr 09 15:43:42 CST 2018
     */
    public String getDeviceSecret() {
        return deviceSecret;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ali_devices.device_secret
     *
     * @param deviceSecret the value for ali_devices.device_secret
     *
     * @mbg.generated Mon Apr 09 15:43:42 CST 2018
     */
    public void setDeviceSecret(String deviceSecret) {
        this.deviceSecret = deviceSecret == null ? null : deviceSecret.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ali_devices.status
     *
     * @return the value of ali_devices.status
     *
     * @mbg.generated Mon Apr 09 15:43:42 CST 2018
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ali_devices.status
     *
     * @param status the value for ali_devices.status
     *
     * @mbg.generated Mon Apr 09 15:43:42 CST 2018
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ali_devices.create_at
     *
     * @return the value of ali_devices.create_at
     *
     * @mbg.generated Mon Apr 09 15:43:42 CST 2018
     */
    public Date getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ali_devices.create_at
     *
     * @param createAt the value for ali_devices.create_at
     *
     * @mbg.generated Mon Apr 09 15:43:42 CST 2018
     */
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ali_devices.update_at
     *
     * @return the value of ali_devices.update_at
     *
     * @mbg.generated Mon Apr 09 15:43:42 CST 2018
     */
    public Date getUpdateAt() {
        return updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ali_devices.update_at
     *
     * @param updateAt the value for ali_devices.update_at
     *
     * @mbg.generated Mon Apr 09 15:43:42 CST 2018
     */
    public void setUpdateAt(Date updateAt) {
        this.updateAt = updateAt;
    }
}