package turing.turingcodey.data.model;

import java.util.Date;

public class Work {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column works.id
     *
     * @mbg.generated Tue Apr 17 17:33:26 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column works.user_id
     *
     * @mbg.generated Tue Apr 17 17:33:26 CST 2018
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column works.work_name
     *
     * @mbg.generated Tue Apr 17 17:33:26 CST 2018
     */
    private String workName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column works.description
     *
     * @mbg.generated Tue Apr 17 17:33:26 CST 2018
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column works.code
     *
     * @mbg.generated Tue Apr 17 17:33:26 CST 2018
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column works.mode
     *
     * @mbg.generated Tue Apr 17 17:33:26 CST 2018
     */
    private Byte mode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column works.device_serial_number
     *
     * @mbg.generated Tue Apr 17 17:33:26 CST 2018
     */
    private String deviceSerialNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column works.graph
     *
     * @mbg.generated Tue Apr 17 17:33:26 CST 2018
     */
    private String graph;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column works.components
     *
     * @mbg.generated Tue Apr 17 17:33:26 CST 2018
     */
    private String components;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column works.is_deleted
     *
     * @mbg.generated Tue Apr 17 17:33:26 CST 2018
     */
    private Byte isDeleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column works.is_public
     *
     * @mbg.generated Tue Apr 17 17:33:26 CST 2018
     */
    private Byte isPublic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column works.cover_image
     *
     * @mbg.generated Tue Apr 17 17:33:26 CST 2018
     */
    private String coverImage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column works.create_time
     *
     * @mbg.generated Tue Apr 17 17:33:26 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column works.update_time
     *
     * @mbg.generated Tue Apr 17 17:33:26 CST 2018
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column works.work_type
     *
     * @mbg.generated Tue Apr 17 17:33:26 CST 2018
     */
    private Byte workType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column works.id
     *
     * @return the value of works.id
     *
     * @mbg.generated Tue Apr 17 17:33:26 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column works.id
     *
     * @param id the value for works.id
     *
     * @mbg.generated Tue Apr 17 17:33:26 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column works.user_id
     *
     * @return the value of works.user_id
     *
     * @mbg.generated Tue Apr 17 17:33:26 CST 2018
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column works.user_id
     *
     * @param userId the value for works.user_id
     *
     * @mbg.generated Tue Apr 17 17:33:26 CST 2018
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column works.work_name
     *
     * @return the value of works.work_name
     *
     * @mbg.generated Tue Apr 17 17:33:26 CST 2018
     */
    public String getWorkName() {
        return workName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column works.work_name
     *
     * @param workName the value for works.work_name
     *
     * @mbg.generated Tue Apr 17 17:33:26 CST 2018
     */
    public void setWorkName(String workName) {
        this.workName = workName == null ? null : workName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column works.description
     *
     * @return the value of works.description
     *
     * @mbg.generated Tue Apr 17 17:33:26 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column works.description
     *
     * @param description the value for works.description
     *
     * @mbg.generated Tue Apr 17 17:33:26 CST 2018
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column works.code
     *
     * @return the value of works.code
     *
     * @mbg.generated Tue Apr 17 17:33:26 CST 2018
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column works.code
     *
     * @param code the value for works.code
     *
     * @mbg.generated Tue Apr 17 17:33:26 CST 2018
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column works.mode
     *
     * @return the value of works.mode
     *
     * @mbg.generated Tue Apr 17 17:33:26 CST 2018
     */
    public Byte getMode() {
        return mode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column works.mode
     *
     * @param mode the value for works.mode
     *
     * @mbg.generated Tue Apr 17 17:33:26 CST 2018
     */
    public void setMode(Byte mode) {
        this.mode = mode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column works.device_serial_number
     *
     * @return the value of works.device_serial_number
     *
     * @mbg.generated Tue Apr 17 17:33:26 CST 2018
     */
    public String getDeviceSerialNumber() {
        return deviceSerialNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column works.device_serial_number
     *
     * @param deviceSerialNumber the value for works.device_serial_number
     *
     * @mbg.generated Tue Apr 17 17:33:26 CST 2018
     */
    public void setDeviceSerialNumber(String deviceSerialNumber) {
        this.deviceSerialNumber = deviceSerialNumber == null ? null : deviceSerialNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column works.graph
     *
     * @return the value of works.graph
     *
     * @mbg.generated Tue Apr 17 17:33:26 CST 2018
     */
    public String getGraph() {
        return graph;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column works.graph
     *
     * @param graph the value for works.graph
     *
     * @mbg.generated Tue Apr 17 17:33:26 CST 2018
     */
    public void setGraph(String graph) {
        this.graph = graph == null ? null : graph.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column works.components
     *
     * @return the value of works.components
     *
     * @mbg.generated Tue Apr 17 17:33:26 CST 2018
     */
    public String getComponents() {
        return components;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column works.components
     *
     * @param components the value for works.components
     *
     * @mbg.generated Tue Apr 17 17:33:26 CST 2018
     */
    public void setComponents(String components) {
        this.components = components == null ? null : components.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column works.is_deleted
     *
     * @return the value of works.is_deleted
     *
     * @mbg.generated Tue Apr 17 17:33:26 CST 2018
     */
    public Byte getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column works.is_deleted
     *
     * @param isDeleted the value for works.is_deleted
     *
     * @mbg.generated Tue Apr 17 17:33:26 CST 2018
     */
    public void setIsDeleted(Byte isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column works.is_public
     *
     * @return the value of works.is_public
     *
     * @mbg.generated Tue Apr 17 17:33:26 CST 2018
     */
    public Byte getIsPublic() {
        return isPublic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column works.is_public
     *
     * @param isPublic the value for works.is_public
     *
     * @mbg.generated Tue Apr 17 17:33:26 CST 2018
     */
    public void setIsPublic(Byte isPublic) {
        this.isPublic = isPublic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column works.cover_image
     *
     * @return the value of works.cover_image
     *
     * @mbg.generated Tue Apr 17 17:33:26 CST 2018
     */
    public String getCoverImage() {
        return coverImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column works.cover_image
     *
     * @param coverImage the value for works.cover_image
     *
     * @mbg.generated Tue Apr 17 17:33:26 CST 2018
     */
    public void setCoverImage(String coverImage) {
        this.coverImage = coverImage == null ? null : coverImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column works.create_time
     *
     * @return the value of works.create_time
     *
     * @mbg.generated Tue Apr 17 17:33:26 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column works.create_time
     *
     * @param createTime the value for works.create_time
     *
     * @mbg.generated Tue Apr 17 17:33:26 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column works.update_time
     *
     * @return the value of works.update_time
     *
     * @mbg.generated Tue Apr 17 17:33:26 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column works.update_time
     *
     * @param updateTime the value for works.update_time
     *
     * @mbg.generated Tue Apr 17 17:33:26 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column works.work_type
     *
     * @return the value of works.work_type
     *
     * @mbg.generated Tue Apr 17 17:33:26 CST 2018
     */
    public Byte getWorkType() {
        return workType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column works.work_type
     *
     * @param workType the value for works.work_type
     *
     * @mbg.generated Tue Apr 17 17:33:26 CST 2018
     */
    public void setWorkType(Byte workType) {
        this.workType = workType;
    }
}