package turing.turingcodey.data.dao;

import turing.turingcodey.data.model.AliDevice;

public interface AliDeviceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ali_devices
     *
     * @mbg.generated Mon Apr 09 15:43:42 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ali_devices
     *
     * @mbg.generated Mon Apr 09 15:43:42 CST 2018
     */
    int insert(AliDevice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ali_devices
     *
     * @mbg.generated Mon Apr 09 15:43:42 CST 2018
     */
    int insertSelective(AliDevice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ali_devices
     *
     * @mbg.generated Mon Apr 09 15:43:42 CST 2018
     */
    AliDevice selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ali_devices
     *
     * @mbg.generated Mon Apr 09 15:43:42 CST 2018
     */
    int updateByPrimaryKeySelective(AliDevice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ali_devices
     *
     * @mbg.generated Mon Apr 09 15:43:42 CST 2018
     */
    int updateByPrimaryKey(AliDevice record);
}