package turing.turingcodey.data.dao;

import turing.turingcodey.data.model.Device;

public interface DeviceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devices
     *
     * @mbg.generated Tue Apr 03 10:44:02 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devices
     *
     * @mbg.generated Tue Apr 03 10:44:02 CST 2018
     */
    int insert(Device record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devices
     *
     * @mbg.generated Tue Apr 03 10:44:02 CST 2018
     */
    int insertSelective(Device record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devices
     *
     * @mbg.generated Tue Apr 03 10:44:02 CST 2018
     */
    Device selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devices
     *
     * @mbg.generated Tue Apr 03 10:44:02 CST 2018
     */
    int updateByPrimaryKeySelective(Device record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devices
     *
     * @mbg.generated Tue Apr 03 10:44:02 CST 2018
     */
    int updateByPrimaryKey(Device record);
}