package turing.turingcodey.data.dao;

import turing.turingcodey.data.model.UserDevice;

public interface UserDeviceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_device
     *
     * @mbg.generated Tue Apr 03 10:44:02 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_device
     *
     * @mbg.generated Tue Apr 03 10:44:02 CST 2018
     */
    int insert(UserDevice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_device
     *
     * @mbg.generated Tue Apr 03 10:44:02 CST 2018
     */
    int insertSelective(UserDevice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_device
     *
     * @mbg.generated Tue Apr 03 10:44:02 CST 2018
     */
    UserDevice selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_device
     *
     * @mbg.generated Tue Apr 03 10:44:02 CST 2018
     */
    int updateByPrimaryKeySelective(UserDevice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_device
     *
     * @mbg.generated Tue Apr 03 10:44:02 CST 2018
     */
    int updateByPrimaryKey(UserDevice record);
}